# Generated by Django 6.0.2 on 2026-05-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_category_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/%d', verbose_name='Imagem do Produto'),
        ),
    ]
