"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('A variável de ambiente SECRET_KEY não foi encontrada!')

DEBUG = os.getenv('DJANGO_DEBUG', 'False') == 'True'
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'produtos',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middlewares.PerformanceLogMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # ─── API-FIRST ─────────────────────────────────────────────
        # O diretório templates/ foi removido nesta branch.
        # A aplicação migrou para REST API com DRF — o front-end
        # (React) é desacoplado e consome JSON. Templates só existem
        # para o admin do Django e apps de terceiros (APP_DIRS=True).
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('MYSQL_DATABASE'),
        'USER': os.getenv('MYSQL_USER'),
        'PASSWORD': os.getenv('MYSQL_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

AUTH_USER_MODEL = 'users.User'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ─────────────────────────────────────────────────────────────────────
# DRF (Django REST Framework) — Configurações Globais da API
# ─────────────────────────────────────────────────────────────────────
# DEFAULT_AUTHENTICATION_CLASSES:
#   Define o método de autenticação PADRÃO para TODOS os endpoints.
#   JWTAuthentication → lê o token do header Authorization: Bearer <token>
#   O Simple JWT se acopla ao django.contrib.auth — usa o User model
#   configurado em AUTH_USER_MODEL para validar o token.
#
# DEFAULT_PAGINATION_CLASS:
#   Toda listagem retorna autoaticamente:
#   {
#       "count": 150,         ← total de registros
#       "next": "...page=3",  ← URL da próxima página (ou null)
#       "previous": "...page=1", ← URL da página anterior (ou null)
#       "results": [...]      ← dados da página atual
#   }
#   PAGE_SIZE: 20 itens por página.
#
# DEFAULT_FILTER_BACKENDS:
#   Filtros habilitados globalmente. Cada ViewSet pode sobrescrever.
#   - DjangoFilterBackend: filtro exato (?category=uuid)
#   - SearchFilter: busca textual (?search=termo)
#   - OrderingFilter: ordenação (?ordering=price,-created_at)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# ─────────────────────────────────────────────────────────────────────
# SIMPLE JWT — Configuração de Tokens
# ─────────────────────────────────────────────────────────────────────
# ─── ANATOMIA DO JWT ──────────────────────────────────────────────
# Todo JWT tem 3 partes separadas por ponto (.):
#
#   HEADER.PAYLOAD.SIGNATURE
#
# 1. HEADER (decodificado):
#    {"alg": "HS256", "typ": "JWT"}
#    → Algoritmo de assinatura (HMAC-SHA256)
#
# 2. PAYLOAD (decodificado):
#    {"token_type": "access", "exp": 1717000000, "user_id": "...", ...}
#    → Dados do usuário e metadados do token
#
# 3. SIGNATURE:
#    HMAC-SHA256(base64url(header) + "." + base64url(payload), SECRET_KEY)
#    → A SECRET_KEY do Django ASSINA o token
#    → Se o payload for ALTERADO no cliente, a assinatura não confere
#    → O servidor rejeita o token → acesso negado
#
# ─── ACCESS vs REFRESH (Estratégia de Mitigação) ────────────────
# ACCESS_TOKEN_LIFETIME (60min):
#   Token "da sessão". Enviado em toda requisição no header.
#   Curto → se vazar, a janela de ataque é pequena.
#
# REFRESH_TOKEN_LIFETIME (7d):
#   Token para obter NOVOS access tokens (via /api/token/refresh).
#   Longo → evita que o usuário precise logar toda hora.
#   Armazenado em local seguro (httpOnly cookie ou secure storage).
#
# ROTATE_REFRESH_TOKENS = True:
#   Cada vez que o refresh é usado, UM NOVO refresh é gerado.
#   O anterior é invalidado (se BLACKLIST_AFTER_ROTATION = True).
#   Isso impede reuso de tokens roubados.
#
# Blacklist:
#   Para usar, adicione 'rest_framework_simplejwt.token_blacklist'
#   em INSTALLED_APPS e rode migrate.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
